
import __ASTRO_IMAGE_IMPORT_250ziM from "../../assets/blog/accessibilita-web.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Faccessibilita-web.md";
import __ASTRO_IMAGE_IMPORT_Z1F7LyK from "../../assets/blog/cosa-vuol-dire-sito-lento.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcosa-vuol-dire-sito-lento.md";
import __ASTRO_IMAGE_IMPORT_Z1wIgH2 from "../../assets/blog/google-business-profile.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoogle-business-profile-cos-e-e-come-usarlo.md";
import __ASTRO_IMAGE_IMPORT_Z1hoFz4 from "../../assets/blog/lai-puo-fare-il-mio-sito-web.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flai-puo-fare-il-mio-sito-web.md";
import __ASTRO_IMAGE_IMPORT_2aJ8Gv from "../../assets/blog/perche-il-sito-non-si-trova-su-google.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fperche-il-sito-non-si-trova-su-google.md";
import __ASTRO_IMAGE_IMPORT_Z1lPXRd from "../../assets/blog/perche-la-tua-attivita-ha-bisogno-di-un-sito-web.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fperche-la-tua-attivita-ha-bisogno-di-un-sito-web.md";
import __ASTRO_IMAGE_IMPORT_Z8hQur from "../../assets/blog/quanto-costa-un-sito-web.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fquanto-costa-un-sito-web.md";
import __ASTRO_IMAGE_IMPORT_ZlHzrI from "../../assets/blog/social-media-vs-sito-web.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsocial-media-vs-sito-web.md";
export default new Map([["../../assets/blog/accessibilita-web.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Faccessibilita-web.md", __ASTRO_IMAGE_IMPORT_250ziM], ["../../assets/blog/cosa-vuol-dire-sito-lento.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcosa-vuol-dire-sito-lento.md", __ASTRO_IMAGE_IMPORT_Z1F7LyK], ["../../assets/blog/google-business-profile.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgoogle-business-profile-cos-e-e-come-usarlo.md", __ASTRO_IMAGE_IMPORT_Z1wIgH2], ["../../assets/blog/lai-puo-fare-il-mio-sito-web.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flai-puo-fare-il-mio-sito-web.md", __ASTRO_IMAGE_IMPORT_Z1hoFz4], ["../../assets/blog/perche-il-sito-non-si-trova-su-google.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fperche-il-sito-non-si-trova-su-google.md", __ASTRO_IMAGE_IMPORT_2aJ8Gv], ["../../assets/blog/perche-la-tua-attivita-ha-bisogno-di-un-sito-web.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fperche-la-tua-attivita-ha-bisogno-di-un-sito-web.md", __ASTRO_IMAGE_IMPORT_Z1lPXRd], ["../../assets/blog/quanto-costa-un-sito-web.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fquanto-costa-un-sito-web.md", __ASTRO_IMAGE_IMPORT_Z8hQur], ["../../assets/blog/social-media-vs-sito-web.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fsocial-media-vs-sito-web.md", __ASTRO_IMAGE_IMPORT_ZlHzrI]]);
		