// Automatically generated by astro-icon
// dc7c8053d5c7f720a2f76b7d70da7d9a590a8a0c5c8a4ea54a324e84531e81c2

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "astro"
		| "figma"
		| "github"
		| "linkedin"
		| "messaggio"
		| "progetti";
}