// Automatically generated by astro-icon
// a1bf3a22a759275c116487b1ebb6edb5839d41d40b7df2b5e721fc320f83b133

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "astro"
		| "blog"
		| "figma"
		| "github"
		| "linkedin"
		| "messaggio"
		| "persona"
		| "progetti";
}