// Automatically generated by astro-icon
// b2284307924ebdd344431205f2d76a050eaa9b17c44253b6095fa519a28e152e

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "figma"
		| "github"
		| "linkedin"
		| "messaggio"
		| "progetti";
}